# This workflow validates pushes to main branch with end2end tests.
name: E2E Tests

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      ref:
        description: |
          ref: the branch, tag or SHA to checkout.
          If empty, the ref is inferred from the event that triggered the workflow.
        required: false
        default: ''
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  end-to-end-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        path:
          - ./
          - ./modules/clusters
          - ./modules/required_infra
          - ./modules/pcluster_api
          - ./examples/api_only
          - ./examples/cluster_only
          - ./examples/required_infra
          - ./examples/slurm_required
        terraform:
          - 1.5.7
          - 1.8.0
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - name: Setup Terraform ${{ matrix.terraform }}
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false
      - name: Checkout Provider Repository
        uses: actions/checkout@v4
        with:
          repository: aws-tf/terraform-provider-aws-parallelcluster
          ref: main
          path: provider
      - name: Setup Go 1.22.0
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.0
      - name: Install Provider
        run: |
          cd provider
          make install
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.ACTION_E2E_TESTS_ROLE }}
          role-session-name: GitHub_TerraformModuleAwsParallelCluster_End2EndTests
      - name: Terraform Init
        run: cd ${{ matrix.path }} && terraform init -backend-config="bucket=${{ secrets.ACTION_E2E_TESTS_BUCKET }}"
        timeout-minutes: 5
      - name: Terraform Test
        run: cd ${{ matrix.path }} && terraform test
        timeout-minutes: 60
